name: Build and Deploy Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.docker/cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build Docker image
        run: |
          docker build -t prjecmm-image .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag prjecmm-image kaikymoura/prjecmm-image:latest
          docker push kaikymoura/prjecmm-image:latest

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name projeto-ecommerce kaikymoura/prjecmm-image:latest

      # - name: Verify application is running
      #   run: |
      #     curl -f http://localhost:3000 || exit 1
